baseurl: /
languageCode: en-us
title: Chencheng Mao
theme: hugo-ivy
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
preserveTaxonomyNames: true
footnotereturnlinkcontents: ↩
enableGitInfo: true

permalinks:
  note: /note/:year/:month/:day/:slug/
  post: /post/:year/:month/:day/:slug/
menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "CV"
      url: "/CV/"
      weight: 2
    - name: "Experiences"
      url: "/experience/"
      weight: 2
    - name: "Categories"
      url: "/categories/"
      weight: 3
    - name: "Tags"
      url: "/tags/"
      weight: 4

params:
  description: "等晴天，等雨天，等待你给我意外"
  footer: "&copy; [Chencheng Mao](https://vegetarian0fish.org) 2002-{Year} | [Github](https://github.com/mcc0612mcc0612)"
  highlightjsLang: ["latex"]
  highlightjsTheme: "github"
  highlightjsVersion: "11.7.0"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
